### ISSUE TITLE
Metaclass workaround fails on Python 3.6.3

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/community-plugins-mhapi#1]
After update to Python 3.6.3, the "metaclass workaround" seems to fail (I can't rember, I have seen this issue before):

> Traceback (most recent call last):
>   File "./core/mhmain.py", line 548, in loadPlugin
>     module = imp.load_module(name, fp, pathname, description)
>   File "/usr/lib/python3.6/imp.py", line 245, in load_module
>     return load_package(name, filename)
>   File "/usr/lib/python3.6/imp.py", line 217, in load_package
>     return _load(spec)
>   File "<frozen importlib._bootstrap>", line 684, in _load
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "plugins/1_mhapi/__init__.py", line 5, in <module>
>     from .api import API
>   File "plugins/1_mhapi/api.py", line 3, in <module>
>     from .namespace import NameSpace
>   File "plugins/1_mhapi/namespace.py", line 22, in <module>
>     class NameSpace(classCompat(ABCMeta)):
>   File "plugins/1_mhapi/namespace.py", line 19, in classCompat
>     return type.__new__(uglyWorkaroundClass,'uglyWorkaroundClass')
> TypeError: type.__new__() takes exactly 3 arguments (1 given)

Perhaps we should permanently keep different branches for P2 and P3 instead of trying to make code that runs on both Python versions?

**Comment by Aranuvir** [comment]
Not sure what I'm doing here or if I'm doing things correctly but my latest commit should fix the issue.

**Comment by joepal1976** [comment]
Fixed in https://github.com/makehumancommunity/community-plugins-mhapi/commit/7f2ac3789f64c13f1857127ce144ba42a4345f70
