### ISSUE TITLE
NoneType object has no attribute name ' mhapi'

### ISSUE THREAD

**Issue by charchitd** [makehumancommunity/community-plugins-mhapi#10]
After placed the !_mhapi folder into plugin as instructed i am executing this code to mass export the following characters.
#code
from core import G
mhapi = G.app.mhapi

human = mhapi.internals.getHuman()
print("Processing...")
human.load("Middle_aged Causcasian Male\modelA001.mhm", True)
mhapi.export.exportAsFBX("/Middle_aged Causcasian Male/New folder/modelA001.fbx")
print("Done")

but I am getting the following error on this:
![error2](https://user-images.githubusercontent.com/30744323/116508553-4264ae80-a8df-11eb-8270-d665bd06d071.PNG)

Kindly help me with this
Thank you

**Comment by Aranuvir** [comment]
Again: Here is the bug tracker and not the help desk! This is still not a bug! 
You **cannot** access that data outside the context of MakeHuman!!
